### ISSUE TITLE
LEDs not working

### ISSUE THREAD

**Issue by 0xfgarcia** [FreeJoy-Team/FreeJoyConfiguratorQt#1]
Hi,

LEDs do not work with the Qt version of the configurator, with the "traditional" version they work. 

I attach the configuration file.

Thanks!

![imagen](https://user-images.githubusercontent.com/2559586/94142414-8a65b380-fe6e-11ea-9d44-de122f5ca88d.png)

![imagen](https://user-images.githubusercontent.com/2559586/94142546-bed96f80-fe6e-11ea-8b09-5e69007d449c.png)

![imagen](https://user-images.githubusercontent.com/2559586/94142447-981b3900-fe6e-11ea-817a-eb7f2aae77af.png)

[New QT Configurator.zip](https://github.com/FreeJoy-Team/FreeJoyConfiguratorQt/files/5275809/New.QT.Configurator.zip)

**Comment by Reksotiv** [comment]
Hi, could you test new version https://github.com/FreeJoy-Team/FreeJoyConfiguratorQt/releases ?

**Comment by 0xfgarcia** [comment]
Solved.

Thanks!
