### ISSUE TITLE
Installation Process

### ISSUE THREAD

**Issue by ivannunyadambiz** [FreeJoy-Team/FreeJoyConfiguratorQt#13]
> Linux
> Downloand and unpack .tar.xz

which .tar.gz ?

**Comment by Reksotiv** [comment]
![image](https://user-images.githubusercontent.com/29454172/117015342-4be48100-acfa-11eb-93a0-b634e30e90fc.png)
![image](https://user-images.githubusercontent.com/29454172/117015433-674f8c00-acfa-11eb-808e-f15795811885.png)

**Comment by ivannunyadambiz** [comment]
thanks. :facepalm:
