### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by Porshe2010** [FreeJoy-Team/FreeJoyConfiguratorQt#3]
hello
I do
> qmake
> make

and I succeed

g ++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DWIN_DESKTOP -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -It / usr / share / qcs ++. -I / usr / include / qt4 / QtCore -I / usr / include / qt4 / QtGui -I / usr / include / qt4 -I. -I. -o centered_cbox.o centered_cbox.cpp
In file included from centered_cbox.cpp: 1:
centered_cbox.h: 13: error: expected ‘;’ before ‘override’
centered_cbox.h: 10: error: ‘nullptr’ was not declared in this scope
centered_cbox.cpp: 15: error: no ‘void CenteredCBox :: paintEvent (QPaintEvent *)’ member function declared in class ‘CenteredCBox’
make: *** [centered_cbox.o] Error 1

**Comment by Reksotiv** [comment]
Hello. Try install Qt5
`sudo apt-get install qt5-default`

**Comment by Porshe2010** [comment]
Thank you.  I also wanted to ask you.  Is it difficult to connect lcd to your project like here?  http://generichid.sourceforge.net/

**Comment by Reksotiv** [comment]
LCD is not supported. The configurator is written in Qt. It is not difficult to write a configurator and it can be in Qt, [WPF](https://github.com/FreeJoy-Team/FreeJoyConfigurator), etc. This is just a graphical interface that allows you to configure the [microcontroller](https://github.com/FreeJoy-Team/FreeJoy). It is his firmware that needs to be changed and this is more difficult. I don't think this project will support LCD display.
