### ISSUE TITLE
AppImage Segmentation fault in Arch Linux (Linux 5.11.1-arch1-1)

### ISSUE THREAD

**Issue by imShara** [FreeJoy-Team/FreeJoyConfiguratorQt#8]
Tried last and first version

```
65206 Segmentation fault      (core dumped) "$BASE_DIR/usr/bin/FreeJoyQt" "$@"
```

Do not know how to debug AppImages, but may this helps:

```sh
./FreeJoyQt-x86_64.AppImage --appimage-extract && ./squashfs-root/usr/bin/FreeJoyQt
```
```
./squashfs-root/usr/bin/FreeJoyQt: symbol lookup error: /home/user/Projects/Joy/FreeJoyQt-v1.7.0b1-Linux-x64-AppImage/squashfs-root/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5: undefined symbol: _ZN22QWindowSystemInterface24setPlatformFiltersEventsEb, version Qt_5_PRIVATE_API
```

**Comment by Reksotiv** [comment]
Hello. This is a known issue. At the moment linux build only works in mint and ubuntu. You can build from source.
`sudo apt-get install qt5-default`
`sudo apt-get install libudev-dev libusb-1.0-0-dev libfox-1.6-dev`
`sudo apt-get install libxcb-xinerama0`
`qmake`
`make`

**Comment by imShara** [comment]
Nice tip, thanks. Will create AUR package then

**Comment by Reksotiv** [comment]
I updated AppImage. Can you check it?

**Comment by pipes80-collab** [comment]
I can confirm than work on Debian 5.10.0.3

**Comment by Reksotiv** [comment]
Thanks

**Comment by imShara** [comment]
> I updated AppImage. Can you check it?

Archlinux latest, works. Thanks!
