### ISSUE TITLE
assetto corsa debian

### ISSUE THREAD

**Issue by pipes80-collab** [FreeJoy-Team/FreeJoyConfiguratorQt#9]
I'm having trouble setting the throttle and brake in racing trim under debian 5.10.0.3 linux kernel

**Comment by vostrenkov** [comment]
Are you able to get buttons presses it the system?

**Comment by pipes80-collab** [comment]
Yes but not able in game

**Comment by pipes80-collab** [comment]
the problem only occurs under debian

**Comment by Reksotiv** [comment]
[FreeJoy-Team/FreeJoy/issues/102](https://github.com/FreeJoy-Team/FreeJoy/issues/102)

**Comment by ufocia** [comment]
> Yes but not able in game

If jstest-gtk shows the right actions then the problem is in the game or perhaps some permissions and not the joystick.

**Comment by pipes80-collab** [comment]
> > Yes but not able in game
> 
> If jstest-gtk shows the right actions then the problem is in the game or perhaps some permissions and not the joystick.

solved after install jstest-gtk
